version: 2

project_name: test-gha

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

dockers:
  - image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:latest-amd64"
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}-arm64v8"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64v8"
      - "ghcr.io/marcbran/{{ .ProjectName }}:latest-arm64v8"
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: ghcr.io/marcbran/{{ .ProjectName }}:{{ .Tag }}
    image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
  - name_template: ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}
    image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}-arm64v8"
  - name_template: ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
    image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}-arm64v8"
  - name_template: ghcr.io/marcbran/{{ .ProjectName }}:latest
    image_templates:
      - "ghcr.io/marcbran/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/marcbran/{{ .ProjectName }}:latest-arm64v8"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
