version: 2

project_name: test-gha

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: darwin
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

release:
  disable: true
